export const TAU = Math.PI * 2;

export const MODEL_META = {
  tanaka: {
    label: "Dan Tanaka swarm oscillator",
    title: "Dan Tanaka membrane candidate",
    equation: "dpsi, dr from exp(−R) chemotactic phase coupling",
    story:
      "Dan Tanaka の chemotactic / swarm oscillator 縮約モデルに絞った計器です。位相差と距離に依存する指数減衰相互作用で、膜・果実断面・clustered clusters を探索します。",
    controlTitle: "Tanaka",
  },
};

export const PUBLIC_MODEL = "tanaka";

export const PRESETS = {
  tanaka: [
    {
      id: "tanaka_membrane",
      label: "Membrane / fruit-section",
      description: "Tanaka–Iida RIMS の membrane 近傍。ゆっくり積分すると薄い膜状境界や果実断面風の分離を狙う。",
      guide: {
        source: "Tanaka–Iida の RIMS 論文 [2]",
        role: "膜状境界や果実断面状の分離を探す中心プリセット。",
        watch: "まず phase color が空間的に分かれ、長時間で薄い境界や袋状の輪郭が残るかを見る。",
        note: "section-of-fruit が t=1e3 から 1e4 付近で出る可能性があるため、ブラウザでは粒子数を増やして長めに観察する。",
        tags: ["membrane", "fruit-section", "RIMS"],
        paperParams: {
          label: "RIMS Fig. 1 / membrane near",
          n: "30 in Fig. 1; 50 examples also reported",
          dt: "not specified for browser Euler step",
          c1: 1.3,
          c2: 3.0,
          c3: 0.02,
          alpha: 0.0,
          L: 10.0,
          note: "Browser N=220 is a display choice, not the reported paper N.",
        },
      },
      params: {
        n: 220,
        dt: 0.045,
        stepsPerFrame: 5,
        seed: 37,
        initScale: 10,
        viewScale: 10,
        particleSize: 4.2,
        trailFade: 0.075,
        trailGain: 0.92,
        stirStrength: 0.7,
        c1: 1.3,
        c2: 3.0,
        c3: 0.02,
        alpha: 0.0,
        boxSize: 10.0,
        periodic: true,
        velocityClamp: 1.4,
      },
    },
    {
      id: "tanaka_clustered_clusters",
      label: "PRL clustered clusters",
      description: "Tanaka PRL 2007 の clustered clusters 定性的ターゲット。クラスターの同期と反位相的配置を見る。",
      guide: {
        source: "Tanaka PRL 2007 [1]",
        role: "複数の小クラスターが生まれ、それぞれの位相関係と移動を観察するプリセット。",
        watch: "近い色の粒子がまとまり、別クラスターとの距離や反位相的な配置が変わっていくかを見る。",
        note: "alpha=1.6 と大きめの c3 が特徴。膜よりも動きが速く、クラスターの生成消滅を見やすい。",
        tags: ["PRL 2007", "clustered clusters", "alpha lag"],
        paperParams: {
          label: "PRL Fig. 1 clustered clusters",
          n: 50,
          dt: "browser integration choice",
          c1: 1.5,
          c2: 1.5,
          c3: 1.5,
          alpha: 1.6,
          L: 30.0,
          note: "Browser N=180 keeps the PRL parameter point but uses a denser visual sample.",
        },
      },
      params: {
        n: 180,
        dt: 0.018,
        stepsPerFrame: 5,
        seed: 11,
        initScale: 30,
        viewScale: 30,
        particleSize: 3.8,
        trailFade: 0.085,
        trailGain: 0.82,
        stirStrength: 0.55,
        c1: 1.5,
        c2: 1.5,
        c3: 1.5,
        alpha: 1.6,
        boxSize: 30.0,
        periodic: true,
        velocityClamp: 3.0,
      },
    },
    {
      id: "tanaka_fireworks",
      label: "Fireworks explorer",
      description: "論文末尾の fireworks / train / stick-slip 系を探すための視覚探索用。厳密再現ではなく触って探すプリセット。",
      guide: {
        source: "Tanaka PTP Supplement 2009 [3]",
        role: "fireworks, train, stick-slip 的な運動を探すための candidate。",
        watch: "中心から外へはじける軌跡、細い列、急停止と再加速のような運動が出るかを見る。",
        note: "厳密な論文再現値ではなく探索用。stir を 0 にすると純粋な初期値依存の挙動を確認しやすい。",
        tags: ["candidate", "fireworks", "motion"],
        paperParams: {
          label: "exploratory candidate",
          n: "not a reported reproduction value",
          dt: "browser integration choice",
          c1: "candidate",
          c2: "candidate",
          c3: "candidate",
          alpha: "candidate",
          L: "candidate",
          note: "This preset is tuned for visual exploration of motion types named in the paper, not a quoted figure parameter set.",
        },
      },
      params: {
        n: 220,
        dt: 0.025,
        stepsPerFrame: 5,
        seed: 91,
        initScale: 16,
        viewScale: 16,
        particleSize: 3.6,
        trailFade: 0.062,
        trailGain: 1.0,
        stirStrength: 0.5,
        c1: 0.92,
        c2: 2.75,
        c3: 0.42,
        alpha: 1.25,
        boxSize: 16.0,
        periodic: true,
        velocityClamp: 2.6,
      },
    },
    {
      id: "tanaka_magnetic_membrane",
      label: "High contrast membrane probe",
      description: "膜境界の可視性を上げるため N と描画をやや増やした探索用。GPU なしでも動く範囲に抑えている。",
      guide: {
        source: "Tanaka–Iida の RIMS 論文 [2]",
        role: "膜候補の境界を見やすくする高コントラスト版。",
        watch: "phase spread が残ったまま最近傍距離が落ち着き、薄い境界線が持続するかを見る。",
        note: "この近傍点は非常に長い時間でも section-of-fruit に届かない例があるため、持続膜 candidate として見る。",
        tags: ["candidate", "persistent membrane", "high contrast"],
        paperParams: {
          label: "RIMS persistent membrane candidate",
          n: "long-run note uses parameter point, not this browser N",
          dt: "not specified for browser Euler step",
          c1: 1.33,
          c2: 2.92,
          c3: 0.02,
          alpha: 0.0,
          L: 10.0,
          note: "Browser N=260 is a high-contrast display choice.",
        },
      },
      params: {
        n: 260,
        dt: 0.038,
        stepsPerFrame: 5,
        seed: 123,
        initScale: 10,
        viewScale: 10,
        particleSize: 3.4,
        trailFade: 0.045,
        trailGain: 1.08,
        stirStrength: 0.36,
        c1: 1.33,
        c2: 2.92,
        c3: 0.02,
        alpha: 0.0,
        boxSize: 10.0,
        periodic: true,
        velocityClamp: 1.2,
      },
    },
    {
      id: "tanaka_rims_phase_a",
      label: "RIMS phase A landmark",
      description: "RIMS の c1,c2 相図に出てくる代表点 A。位相は揃いやすく、位置は離れやすい側のランドマーク。",
      guide: {
        source: "Tanaka–Iida の RIMS c₁,c₂ 相図 [2]",
        role: "c1,c2 scan の代表点 A。membrane 近傍を見る前に、位相引力と位置斥力の組み合わせを確認する。",
        watch: "粒子が同系色へ寄りながら、空間的には広がろうとする傾向を見る。",
        note: "論文の相図では N=20, L=10, c3=0.02, alpha=0。ブラウザでは粒子数を増やして見た目を読みやすくしている。",
        tags: ["RIMS phase map", "phase A", "c1/c2 scan"],
        paperParams: {
          label: "RIMS local phase diagram point A",
          n: 20,
          dt: "scan average after transient; browser step is display choice",
          c1: 0.5,
          c2: 1.5,
          c3: 0.02,
          alpha: 0.0,
          L: 10.0,
          note: "Browser N=160 increases particles for visual readability.",
        },
      },
      params: {
        n: 160,
        dt: 0.045,
        stepsPerFrame: 5,
        seed: 211,
        initScale: 10,
        viewScale: 10,
        particleSize: 3.8,
        trailFade: 0.07,
        trailGain: 0.9,
        stirStrength: 0.45,
        c1: 0.5,
        c2: 1.5,
        c3: 0.02,
        alpha: 0.0,
        boxSize: 10.0,
        periodic: true,
        velocityClamp: 1.2,
      },
    },
    {
      id: "tanaka_rims_phase_b",
      label: "RIMS phase B landmark",
      description: "RIMS の c1,c2 相図に出てくる代表点 B。位置は近づきやすく、位相は反発しやすい側のランドマーク。",
      guide: {
        source: "Tanaka–Iida の RIMS c₁,c₂ 相図 [2]",
        role: "c1,c2 scan の代表点 B。近づく力と位相反発が同時に働くときの凝集傾向を見る。",
        watch: "粒子が集まりつつ、同じ場所の中で色が分かれるかを見る。",
        note: "RIMS paper の二体系解釈では、B は位置に引力、位相に斥力が働く側として説明される。",
        tags: ["RIMS phase map", "phase B", "cluster tendency"],
        paperParams: {
          label: "RIMS local phase diagram point B",
          n: 20,
          dt: "scan average after transient; browser step is display choice",
          c1: 3.0,
          c2: 2.0,
          c3: 0.02,
          alpha: 0.0,
          L: 10.0,
          note: "Browser N=160 increases particles for visual readability.",
        },
      },
      params: {
        n: 160,
        dt: 0.045,
        stepsPerFrame: 5,
        seed: 223,
        initScale: 10,
        viewScale: 10,
        particleSize: 3.8,
        trailFade: 0.075,
        trailGain: 0.9,
        stirStrength: 0.45,
        c1: 3.0,
        c2: 2.0,
        c3: 0.02,
        alpha: 0.0,
        boxSize: 10.0,
        periodic: true,
        velocityClamp: 1.2,
      },
    },
    {
      id: "tanaka_rims_phase_c",
      label: "RIMS phase C landmark",
      description: "RIMS の c1,c2 相図に出てくる代表点 C。位相も位置も近づきやすい側のランドマーク。",
      guide: {
        source: "Tanaka–Iida の RIMS c₁,c₂ 相図 [2]",
        role: "c1,c2 scan の代表点 C。位相引力と位置引力が重なる側を観察する。",
        watch: "色が揃う方向と空間凝集が同時に進むかを見る。",
        note: "c1=6.0, c2=4.0 は従来の -pi..pi スライダー範囲を超えるため、ブラウザの c1/c2 範囲も 0..2π に合わせている。",
        tags: ["RIMS phase map", "phase C", "large c1/c2"],
        paperParams: {
          label: "RIMS local phase diagram point C",
          n: 20,
          dt: "scan average after transient; browser step is display choice",
          c1: 6.0,
          c2: 4.0,
          c3: 0.02,
          alpha: 0.0,
          L: 10.0,
          note: "Browser N=160 increases particles for visual readability.",
        },
      },
      params: {
        n: 160,
        dt: 0.045,
        stepsPerFrame: 5,
        seed: 239,
        initScale: 10,
        viewScale: 10,
        particleSize: 3.8,
        trailFade: 0.075,
        trailGain: 0.9,
        stirStrength: 0.45,
        c1: 6.0,
        c2: 4.0,
        c3: 0.02,
        alpha: 0.0,
        boxSize: 10.0,
        periodic: true,
        velocityClamp: 1.2,
      },
    },
    {
      id: "tanaka_rims_phase_d",
      label: "RIMS phase D landmark",
      description: "RIMS の c1,c2 相図に出てくる代表点 D。位相も位置も反発しやすい側のランドマーク。",
      guide: {
        source: "Tanaka–Iida の RIMS c₁,c₂ 相図 [2]",
        role: "c1,c2 scan の代表点 D。位相反発と位置斥力が重なる側を観察する。",
        watch: "色が混ざったまま空間的に散りやすいか、境界付近で膜的な揺らぎが出るかを見る。",
        note: "RIMS paper では A-D の境界付近に membrane / section-of-fruit が現れるため、D は membrane 近傍の比較点として使いやすい。",
        tags: ["RIMS phase map", "phase D", "repulsive side"],
        paperParams: {
          label: "RIMS local phase diagram point D",
          n: 20,
          dt: "scan average after transient; browser step is display choice",
          c1: 4.0,
          c2: 4.0,
          c3: 0.02,
          alpha: 0.0,
          L: 10.0,
          note: "Browser N=160 increases particles for visual readability.",
        },
      },
      params: {
        n: 160,
        dt: 0.045,
        stepsPerFrame: 5,
        seed: 251,
        initScale: 10,
        viewScale: 10,
        particleSize: 3.8,
        trailFade: 0.075,
        trailGain: 0.9,
        stirStrength: 0.45,
        c1: 4.0,
        c2: 4.0,
        c3: 0.02,
        alpha: 0.0,
        boxSize: 10.0,
        periodic: true,
        velocityClamp: 1.2,
      },
    },
  ],
};

export const COMMON_CONTROLS = [
  { key: "n", label: "N", min: 12, max: 360, step: 1, format: "int", resets: true, hint: "粒子数。多いほど美しいが O(N²) で重くなります。" },
  { key: "dt", label: "dt", min: 0.005, max: 0.12, step: 0.001, format: "fixed3", hint: "Euler 積分の時間刻み。暴れる時は下げます。" },
  { key: "stepsPerFrame", label: "speed", min: 1, max: 8, step: 1, format: "int", hint: "1 フレームあたりの積分ステップ数。" },
  { key: "particleSize", label: "particle glow", min: 1.5, max: 8.0, step: 0.1, format: "fixed1", hint: "粒子の見かけの大きさ。" },
  { key: "trailFade", label: "trail fade", min: 0.015, max: 0.22, step: 0.001, format: "fixed3", hint: "大きいほど軌跡が早く消えます。" },
  { key: "trailGain", label: "trail gain", min: 0.2, max: 1.8, step: 0.01, format: "fixed2", hint: "軌跡の明るさ。" },
  { key: "stirStrength", label: "stir", min: 0.0, max: 1.5, step: 0.01, format: "fixed2", hint: "ドラッグ操作で加える局所的な位相・速度攪拌。" },
];

export const MODEL_CONTROLS = {
  tanaka: [
    { key: "c1", label: "c1", min: 0, max: TAU, step: 0.005, format: "fixed3", hint: "位相方程式のオフセット。RIMS の c1,c2 scan は 0..2π で見ると分かりやすい。" },
    { key: "c2", label: "c2", min: 0, max: TAU, step: 0.005, format: "fixed3", hint: "位置方程式のオフセット。膜候補では 3.0 近傍。" },
    { key: "c3", label: "c3", min: 0.0, max: 2.5, step: 0.001, format: "fixed3", hint: "位置運動の相対速度。膜候補は非常に小さい。" },
    { key: "alpha", label: "alpha", min: 0.0, max: 3.2, step: 0.005, format: "fixed3", hint: "距離に比例する位相遅れ。PRL clustered clusters では 1.6。" },
    { key: "boxSize", label: "box L", min: 3.0, max: 40.0, step: 0.1, format: "fixed1", hint: "周期境界の箱サイズ。変更時は Reset 推奨。" },
    { key: "velocityClamp", label: "velocity cap", min: 0.2, max: 8.0, step: 0.1, format: "fixed1", hint: "Web 表示を守る安全弁。論文式自体にはない可視化用制限。" },
  ],
};
